# filename : pb3-httpd.yml

- 
  name: play3
  hosts: server1
  tasks:
  - name: install the latest version of Apache
    yum:
     name: httpd
     state: latest

  - name: start httpd service
    service:
     name: httpd
     state: started
